# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
defaults: &defaults
  adapter: mysql2
  username: root
  password: root
  host: localhost

development:
  <<: *defaults
  database: lhw_development
  
  
production:
  <<: *defaults
  database: lhw_production

test:
  <<: *defaults
  database: lhw_test
