# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
defaults: &defaults
  adapter: mysql2
  username: root
  password: 
  host: localhost

development:
  <<: *defaults
  database: lhw_development
  
  
production:
  adapter: mysql2
  username: root
  database: lhw_production
  password: lhwict1234
  host: 127.0.0.1
  socket: /var/lib/mysql/mysql.sock

test:
  <<: *defaults
  database: lhw_test
